    <div id="body-login">
        <div id="corpo-login">
            <br>
            <h2>SGTCC</h2>
            Sistema de gerenciamento de TCC
            <div class="grupo-input">
                <form action="/logar" method="POST">
                    <div class="inputs">
                        <label>Login: </label>
                        <input class="input" type="text" name="Usuario" id="Usuario" placeholder="Usuário">
                    </div>
                    <div class="inputs">
                        <label>Senha: </label>
                        <input class="input" type="password" name="Senha" id="Senha" placeholder="Senha">
                    </div>
                    <br>
                    <a href="/cadastrar">Cadastra-se</a>
                    <br>
                    <br>
                    <button class="but">Entrar</button>
                </form>
            </div>
        </div>
    </div>
