<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="styleprincipal.css">
    <title>Tela Principal</title>
</head>

<body>
    <header>
        <div id="tituloprincipal">
            <h3>Sistema de Gerenciamento de Trabalho de Conclusão de Curso-TCC</h3>
            <hr width="630px">
        </div>
        <div id="menuprincipal">
            <a href="/home">Home</a>
            <a href="/orientacoes">Orientações</a>
            <a href="/estrutura">Estrutura do TCC</a>
            <a href="/sair">Sair</a>
        </div>
    </header>
    <div id="corpo-principal">
        <img src="/img/tcc.jpg" width="950px" height="600px">
    </div>
    <footer>
        <div id="declaracoes">
            Sistema de Gerenciamento de Conclusão de Curso-TCC I e II <br>
            Gestão e Orientação de Qualidade <br>
            Contato: (086)999999999 <br>
            E-mail: estacio@estacio.br
        </div>
        <div id="logo-estacio">
            <img src="/img/estacio.png" width="140px" height="90px">
        </div>
    </footer>
</body>

</html>