<header>
        <div id="titulo">
            <h3>Acompanhamento das Orientações de TCC</h3>
            <hr width="450px">
        </div>
        <div id="menu">
            <a href="/home">Home</a>
            <a href="/estrutura">Estrutura do TCC</a>
            <a href="/sair">Sair</a>
        </div>
    </header>
    <div id="corpo-main">
        <div id="cabecalho">
            <div id="logo-cabecalho">
                <img src="/img/tcc.jpg" width="50px" height="50px">
            </div>
            <div id="titulo-cabecalho">
                Informe as Orientações Apresentadas
            </div>
            <hr color="blue">
        </div>
        <form id="form-orientacao" action="/salvar-orientacao" method="POST">
            <div id="grupo-input-orientacao">
                <div class="inputs-orientacao">
                    <label>Orientador:..............</label>
                    <input class="input-orientacao" type="text" name="orientador" id="Matricula">
                </div>
                <div class="inputs-orientacao">
                    <label>Aluno:.....................</label>
                    <input class="input-orientacao" type="text" name="Aluno" id="Aluno"> 
                </div>
            </div>
            <br>
            <hr color="blue">
            <div id="orientacao">
                <textarea name="orientacoes" id="orientacoes" cols="150" rows="10">

                </textarea>
            </div>
            <div id="botao">
                <button class="button">Cadastrar</button>
            </div>
        </form>
    </div>
    <footer>
        <div id="declaracoes">
            Sistema de Gerenciamento de Conclusão de Curso-TCC I e II <br>
            Gestão e Orientação de Qualidade <br>
            Contato: (086)999999999 <br>
            E-mail: estacio@estacio.br
        </div>
        <div id="logo-estacio">
            <img src="/img/estacio.png" width="140px" height="90px">
        </div>
    </footer>