<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>
		<link rel="stylesheet" href="/css/stylelogin.css">
		<link rel="stylesheet" href="/css/styleprincipal.css">
		<link rel="stylesheet" href="/css/style-orientacoes.css">
		<link rel="stylesheet" href="/css/style-estruturatcc.css">
		<link rel="stylesheet" href="/css/cadastro.css">

	</head>

	<body>
		<?= $this->content() ?>
	</body>

</html>